# -*- coding: utf-8 -*-
"""수행시간비교_다항식.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VDqtceixQYu-SPqZCucdyoXi5FYxd3oY
"""

import time, random

random.seed()
n = int(input())
A = list(range(n))
x = random.randint(-1000,1000)
for a in range(n):
	A[a] = random.randint(-1000, 1000)

def evaluate_n2(A, x):
	sum1 = 0
	for i in range(n):
		k=1
		for j in range(i):
			k = k*x
			sum1 += A[a] * k
	return sum1
	# code for O(n^2)-time function

def evaluate_n(A, x):
	sum2 = 0
	k = 1
	for i in range(n):
		k = k*x
		sum2 += A[a] * k
	return sum2
	# code for O(n)-time function

s = time.process_time()
evaluate_n(A,x)
e = time.process_time()
print("O(n)의 수행시간 = ",e-s)

s = time.process_time()
evaluate_n2(A,x)
e = time.process_time()
print("O(n^2)의 수행시간 = ",e-s)